# Generated by Django 4.0.2 on 2022-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delivery_address_orders_profile_remove_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut',
            name='image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
