# Generated by Django 4.0.2 on 2022-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_donut_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donut',
            name='price',
            field=models.FloatField(),
        ),
    ]
