# Generated by Django 4.0.2 on 2022-02-12 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_donut_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='donut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.donut'),
            preserve_default=False,
        ),
    ]
