# Generated by Django 4.0.2 on 2022-02-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='donut',
            new_name='donuts',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='donut',
            new_name='donuts',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='donut',
            new_name='donuts',
        ),
    ]
