# Generated by Django 4.0.2 on 2022-02-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_donut_cart_donuts_rename_donut_order_donuts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='rewards',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
