# Generated by Django 4.0.2 on 2022-02-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address',
            name='email',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
