# Generated by Django 4.0.2 on 2022-02-14 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_delivery_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 18, 2, 11, 118816, tzinfo=utc), verbose_name='order date'),
            preserve_default=False,
        ),
    ]
