# Generated by Django 4.0.2 on 2022-02-15 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_order_ordered_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        # migrations.AlterField(
        #     model_name='cart',
        #     name='donuts',
        #     field=models.ManyToManyField(through='main_app.ItemCart', to='main_app.Donut'),
        # ),
        migrations.AddField(
            model_name='itemcart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cart'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='donut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.donut'),
        ),
    ]
