# Generated by Django 4.0.2 on 2022-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_itemcart_alter_cart_donuts_itemcart_cart_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='cart',
        #     name='donuts',
        #     field=models.ManyToManyField(through='main_app.ItemCart', to='main_app.Donut'),
        # ),
        migrations.AlterField(
            model_name='itemcart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
