# Generated by Django 4.0.2 on 2022-02-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_cart_notes_alter_cart_donuts'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='cart',
        #     name='donuts',
        #     field=models.ManyToManyField(through='main_app.ItemCart', to='main_app.Donut'),
        # ),
        migrations.AlterField(
            model_name='cart',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
