# Generated by Django 4.0.2 on 2022-02-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_cart_donuts_alter_donut_name'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='cart',
        #     name='donuts',
        #     field=models.ManyToManyField(through='main_app.ItemCart', to='main_app.Donut'),
        # ),
        migrations.AlterField(
            model_name='donut',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
